# Generated by Django 3.2.8 on 2021-12-13 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211213_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 17, 39, 34, 309664, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
